version: '3.7'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  notebook1:
    build: pathfinding/
    image: mldev
    shm_size: '15gb'
    ports:
      - "8881:8881"
    environment:
      - PORT=8881
      - NVIDIA_VISIBLE_DEVICES=all
      - VIRTUAL_HOST=notebook1.laps.website
    volumes:
      - notebook1:/workspace
    links:
      - redis
  notebook2:
    image: mldev
    shm_size: '15gb'
    ports:
      - "8882:8882"
    environment:
      - PORT=8882
      - NVIDIA_VISIBLE_DEVICES=all
      - VIRTUAL_HOST=notebook2.laps.website
    volumes:
      - notebook2:/workspace
    links:
      - redis
  redis:
    build: redis/
    image: laps-redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - database:/data

  # For Jan og andre
  notebook3:
    image: mldev
    shm_size: '15gb'
    ports:
      - "8883:8883"
    environment:
      - PORT=8883
      - NVIDIA_VISIBLE_DEVICES=all
      - VIRTUAL_HOST=notebook3.laps.website
    volumes:
      - notebook3:/workspace
    links:
      - redis


volumes:
  notebook1:
    driver: local
  notebook2:
    driver: local
  notebook3:
    driver: local
  database:
    driver: local
